# Server configuration
server.port=8081

# Database configuration

spring.datasource.url=jdbc:h2:file:./data/demo
spring.datasource.username=admin
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create-drop

################################################################
#Default users
user.default.fullName=Sakib Khan
user.default.email=sakibkhan.stud@gmail.com
user.default.password=Sakib123
user.default.street=Mirpur 10, Dhaka
user.default.houseNumber=15
user.default.postalCode=1212
user.default.city=Dhaka
user.default.state=Dhaka

# Other configurations
spring.application.name=VolunterNetwork

#spring.security.user.name=sakib
#spring.security.user.password=sakib123

#server.error.whitelabel.enabled=false

#thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.enabled=true